export interface CategoryGroup {
  name: string;
  slug: string;
  icon: string;
  subcategories: { name: string; slug: string }[];
  featuredBook: { title: string; author: string; slug: string };
}

export const categoryGroups: CategoryGroup[] = [
  {
    name: "Business & Entrepreneurship",
    slug: "business-entrepreneurship",
    icon: "\uD83D\uDCBC",
    subcategories: [
      { name: "Entrepreneurship", slug: "entrepreneurship" },
      { name: "Startups", slug: "startups" },
      { name: "Business Strategy", slug: "business-strategy" },
      { name: "Management", slug: "management" },
      { name: "Leadership", slug: "leadership" },
      { name: "Sales", slug: "sales" },
      { name: "Innovation", slug: "innovation" },
      { name: "Negotiation", slug: "negotiation" },
      { name: "Small Business", slug: "small-business" },
    ],
    featuredBook: { title: "The Lean Startup", author: "Eric Ries", slug: "the-lean-startup" },
  },
  {
    name: "Personal Finance",
    slug: "personal-finance",
    icon: "\uD83D\uDCB0",
    subcategories: [
      { name: "Budgeting", slug: "budgeting" },
      { name: "Investing", slug: "investing" },
      { name: "Saving", slug: "saving" },
      { name: "Retirement", slug: "retirement" },
      { name: "Credit", slug: "credit" },
      { name: "Debt Management", slug: "debt-management" },
      { name: "Financial Planning", slug: "financial-planning" },
      { name: "Wealth Building", slug: "wealth-building" },
    ],
    featuredBook: { title: "Rich Dad Poor Dad", author: "Robert Kiyosaki", slug: "rich-dad-poor-dad" },
  },
  {
    name: "Self Development",
    slug: "self-development",
    icon: "\uD83C\uDF31",
    subcategories: [
      { name: "Habits & Routines", slug: "habits-routines" },
      { name: "Mindfulness", slug: "mindfulness" },
      { name: "Confidence", slug: "confidence" },
      { name: "Time Management", slug: "time-management" },
      { name: "Goal Setting", slug: "goal-setting" },
      { name: "Emotional Intelligence", slug: "emotional-intelligence" },
      { name: "Motivation", slug: "motivation" },
      { name: "Communication", slug: "communication" },
    ],
    featuredBook: { title: "Atomic Habits", author: "James Clear", slug: "atomic-habits" },
  },
  {
    name: "Leadership",
    slug: "leadership",
    icon: "\uD83D\uDC51",
    subcategories: [
      { name: "Executive Leadership", slug: "executive-leadership" },
      { name: "Team Management", slug: "team-management" },
      { name: "Organizational Culture", slug: "organizational-culture" },
      { name: "Decision Making", slug: "decision-making" },
      { name: "Vision & Strategy", slug: "vision-strategy" },
      { name: "Coaching", slug: "coaching" },
    ],
    featuredBook: { title: "Good to Great", author: "Jim Collins", slug: "good-to-great" },
  },
  {
    name: "Technology",
    slug: "technology",
    icon: "\uD83D\uDCBB",
    subcategories: [
      { name: "Artificial Intelligence", slug: "artificial-intelligence" },
      { name: "Programming", slug: "programming" },
      { name: "Cybersecurity", slug: "cybersecurity" },
      { name: "Web Development", slug: "web-development" },
      { name: "Data Science", slug: "data-science" },
      { name: "Cloud Computing", slug: "cloud-computing" },
      { name: "UI/UX Design", slug: "ui-ux-design" },
      { name: "Blockchain", slug: "blockchain" },
    ],
    featuredBook: { title: "The Innovators", author: "Walter Isaacson", slug: "the-innovators" },
  },
  {
    name: "Health & Wellness",
    slug: "health-wellness",
    icon: "\uD83C\uDFE5",
    subcategories: [
      { name: "Fitness", slug: "fitness" },
      { name: "Nutrition", slug: "nutrition" },
      { name: "Mental Health", slug: "mental-health" },
      { name: "Yoga & Meditation", slug: "yoga-meditation" },
      { name: "Diet & Weight Loss", slug: "diet-weight-loss" },
      { name: "Alternative Medicine", slug: "alternative-medicine" },
    ],
    featuredBook: { title: "The Body Keeps the Score", author: "Bessel van der Kolk", slug: "the-body-keeps-the-score" },
  },
  {
    name: "Religion & Inspiration",
    slug: "religion-inspiration",
    icon: "\u2728",
    subcategories: [
      { name: "Christianity", slug: "christianity" },
      { name: "Islam", slug: "islam" },
      { name: "Spirituality", slug: "spirituality" },
      { name: "Inspirational", slug: "inspirational" },
      { name: "Devotionals", slug: "devotionals" },
      { name: "Faith & Doubt", slug: "faith-doubt" },
    ],
    featuredBook: { title: "The Purpose Driven Life", author: "Rick Warren", slug: "the-purpose-driven-life" },
  },
  {
    name: "Biography",
    slug: "biography",
    icon: "\uD83D\uDC64",
    subcategories: [
      { name: "Memoirs", slug: "memoirs" },
      { name: "Autobiographies", slug: "autobiographies" },
      { name: "Historical Figures", slug: "historical-figures" },
      { name: "Celebrities", slug: "celebrities" },
      { name: "Business Leaders", slug: "business-leaders" },
      { name: "Political Leaders", slug: "political-leaders" },
    ],
    featuredBook: { title: "Educated", author: "Tara Westover", slug: "educated" },
  },
  {
    name: "History",
    slug: "history",
    icon: "\uD83D\uDCDC",
    subcategories: [
      { name: "African History", slug: "african-history" },
      { name: "World History", slug: "world-history" },
      { name: "Ancient History", slug: "ancient-history" },
      { name: "Modern History", slug: "modern-history" },
      { name: "Colonial History", slug: "colonial-history" },
      { name: "War & Military", slug: "war-military" },
    ],
    featuredBook: { title: "Things Fall Apart", author: "Chinua Achebe", slug: "things-fall-apart" },
  },
  {
    name: "Politics",
    slug: "politics",
    icon: "\uD83C\uDFDB\uFE0F",
    subcategories: [
      { name: "Political Science", slug: "political-science" },
      { name: "Current Affairs", slug: "current-affairs" },
      { name: "International Relations", slug: "international-relations" },
      { name: "African Politics", slug: "african-politics" },
      { name: "Governance", slug: "governance" },
      { name: "Public Policy", slug: "public-policy" },
    ],
    featuredBook: { title: "We Should All Be Feminists", author: "Chimamanda Ngozi Adichie", slug: "we-should-all-be-feminists" },
  },
  {
    name: "Education",
    slug: "education",
    icon: "\uD83C\uDF93",
    subcategories: [
      { name: "Study Guides", slug: "study-guides" },
      { name: "Academic Writing", slug: "academic-writing" },
      { name: "Test Preparation", slug: "test-preparation" },
      { name: "Teaching", slug: "teaching" },
      { name: "E-Learning", slug: "e-learning" },
      { name: "Study Skills", slug: "study-skills" },
    ],
    featuredBook: { title: "How to Study", author: "Ron Fry", slug: "how-to-study" },
  },
  {
    name: "Science",
    slug: "science",
    icon: "\uD83D\uDD2C",
    subcategories: [
      { name: "Physics", slug: "physics" },
      { name: "Biology", slug: "biology" },
      { name: "Chemistry", slug: "chemistry" },
      { name: "Astronomy", slug: "astronomy" },
      { name: "Environmental Science", slug: "environmental-science" },
      { name: "Mathematics", slug: "mathematics" },
    ],
    featuredBook: { title: "A Brief History of Time", author: "Stephen Hawking", slug: "a-brief-history-of-time" },
  },
  {
    name: "Productivity",
    slug: "productivity",
    icon: "\u26A1",
    subcategories: [
      { name: "Workflow", slug: "workflow" },
      { name: "Focus & Deep Work", slug: "focus-deep-work" },
      { name: "Automation", slug: "automation" },
      { name: "Project Management", slug: "project-management" },
      { name: "Delegation", slug: "delegation" },
    ],
    featuredBook: { title: "Deep Work", author: "Cal Newport", slug: "deep-work" },
  },
  {
    name: "Marketing",
    slug: "marketing",
    icon: "\uD83D\uDCE3",
    subcategories: [
      { name: "Digital Marketing", slug: "digital-marketing" },
      { name: "Social Media Marketing", slug: "social-media-marketing" },
      { name: "Content Marketing", slug: "content-marketing" },
      { name: "Branding", slug: "branding" },
      { name: "SEO", slug: "seo" },
      { name: "Copywriting", slug: "copywriting" },
    ],
    featuredBook: { title: "This Is Marketing", author: "Seth Godin", slug: "this-is-marketing" },
  },
  {
    name: "Fiction",
    slug: "fiction",
    icon: "\uD83D\uDCD6",
    subcategories: [
      { name: "Literary Fiction", slug: "literary-fiction" },
      { name: "Contemporary Fiction", slug: "contemporary-fiction" },
      { name: "Historical Fiction", slug: "historical-fiction" },
      { name: "Science Fiction", slug: "science-fiction" },
      { name: "Short Stories", slug: "short-stories" },
      { name: "Satire", slug: "satire" },
    ],
    featuredBook: { title: "Americanah", author: "Chimamanda Ngozi Adichie", slug: "americanah" },
  },
  {
    name: "Non-Fiction",
    slug: "non-fiction",
    icon: "\uD83D\uDCDA",
    subcategories: [
      { name: "Essays", slug: "essays" },
      { name: "Journalism", slug: "journalism" },
      { name: "True Crime", slug: "true-crime" },
      { name: "Philosophy", slug: "philosophy" },
      { name: "Psychology", slug: "psychology" },
      { name: "Sociology", slug: "sociology" },
    ],
    featuredBook: { title: "Sapiens", author: "Yuval Noah Harari", slug: "sapiens" },
  },
  {
    name: "Romance",
    slug: "romance",
    icon: "\uD83D\uDC95",
    subcategories: [
      { name: "Contemporary Romance", slug: "contemporary-romance" },
      { name: "Historical Romance", slug: "historical-romance" },
      { name: "African Romance", slug: "african-romance" },
      { name: "Romantic Comedy", slug: "romantic-comedy" },
      { name: "New Adult", slug: "new-adult" },
    ],
    featuredBook: { title: "The Wedding Party", author: "Grace Adeyemi", slug: "the-wedding-party" },
  },
  {
    name: "Mystery & Thriller",
    slug: "mystery",
    icon: "\uD83D\uDD0D",
    subcategories: [
      { name: "Crime Thriller", slug: "crime-thriller" },
      { name: "Psychological Thriller", slug: "psychological-thriller" },
      { name: "Detective", slug: "detective" },
      { name: "Espionage", slug: "espionage" },
      { name: "Suspense", slug: "suspense" },
    ],
    featuredBook: { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", slug: "the-girl-with-the-dragon-tattoo" },
  },
  {
    name: "Fantasy",
    slug: "fantasy",
    icon: "\uD83D\uDC09",
    subcategories: [
      { name: "Epic Fantasy", slug: "epic-fantasy" },
      { name: "Urban Fantasy", slug: "urban-fantasy" },
      { name: "African Fantasy", slug: "african-fantasy" },
      { name: "Dark Fantasy", slug: "dark-fantasy" },
      { name: "Mythology", slug: "mythology" },
    ],
    featuredBook: { title: "Black Leopard, Red Wolf", author: "Marlon James", slug: "black-leopard-red-wolf" },
  },
  {
    name: "Children's Books",
    slug: "childrens-books",
    icon: "\uD83E\uDDD2",
    subcategories: [
      { name: "Picture Books", slug: "picture-books" },
      { name: "Early Readers", slug: "early-readers" },
      { name: "Middle Grade", slug: "middle-grade" },
      { name: "Young Adult", slug: "young-adult" },
      { name: "Educational", slug: "educational" },
    ],
    featuredBook: { title: "The Lion and the Mouse", author: "Jerry Pinkney", slug: "the-lion-and-the-mouse" },
  },
  {
    name: "African Literature",
    slug: "african-literature",
    icon: "\uD83C\uDF0D",
    subcategories: [
      { name: "Nigerian Literature", slug: "nigerian-literature" },
      { name: "East African Literature", slug: "east-african-literature" },
      { name: "South African Literature", slug: "south-african-literature" },
      { name: "West African Literature", slug: "west-african-literature" },
      { name: "African Poetry", slug: "african-poetry" },
      { name: "African Essays", slug: "african-essays" },
    ],
    featuredBook: { title: "Half of a Yellow Sun", author: "Chimamanda Ngozi Adichie", slug: "half-of-a-yellow-sun" },
  },
  {
    name: "Poetry",
    slug: "poetry",
    icon: "\uD83C\uDFB6",
    subcategories: [
      { name: "African Poetry", slug: "african-poetry-collection" },
      { name: "Contemporary Poetry", slug: "contemporary-poetry" },
      { name: "Classic Poetry", slug: "classic-poetry" },
      { name: "Spoken Word", slug: "spoken-word" },
      { name: "Haiku", slug: "haiku" },
    ],
    featuredBook: { title: "The Sun and Her Flowers", author: "Rupi Kaur", slug: "the-sun-and-her-flowers" },
  },
  {
    name: "Comics & Graphic Novels",
    slug: "comics-graphic-novels",
    icon: "\uD83D\uDCAA",
    subcategories: [
      { name: "Superhero", slug: "superhero" },
      { name: "Manga", slug: "manga" },
      { name: "Graphic Memoirs", slug: "graphic-memoirs" },
      { name: "African Comics", slug: "african-comics" },
    ],
    featuredBook: { title: "Aya of Yop City", author: "Marguerite Abouet", slug: "aya-of-yop-city" },
  },
  {
    name: "Cookbooks",
    slug: "cookbooks",
    icon: "\uD83C\uDF73",
    subcategories: [
      { name: "African Cuisine", slug: "african-cuisine" },
      { name: "Baking", slug: "baking" },
      { name: "Healthy Cooking", slug: "healthy-cooking" },
      { name: "Quick & Easy", slug: "quick-easy" },
    ],
    featuredBook: { title: "The Nigerian Cookbook", author: "Ozoz Sokoh", slug: "the-nigerian-cookbook" },
  },
  {
    name: "Parenting",
    slug: "parenting",
    icon: "\uD83D\uDC6A",
    subcategories: [
      { name: "Baby & Toddler", slug: "baby-toddler" },
      { name: "Teen Parenting", slug: "teen-parenting" },
      { name: "Family Relationships", slug: "family-relationships" },
      { name: "Education & School", slug: "education-school" },
    ],
    featuredBook: { title: "How to Talk So Kids Will Listen", author: "Adele Faber", slug: "how-to-talk-so-kids-will-listen" },
  },
  {
    name: "Arts & Photography",
    slug: "arts-photography",
    icon: "\uD83C\uDFA8",
    subcategories: [
      { name: "Photography", slug: "photography" },
      { name: "African Art", slug: "african-art" },
      { name: "Design", slug: "design" },
      { name: "Architecture", slug: "architecture" },
    ],
    featuredBook: { title: "The African Art of Storytelling", author: "Chika Okeke-Agulu", slug: "the-african-art-of-storytelling" },
  },
  {
    name: "Travel",
    slug: "travel",
    icon: "\u2708\uFE0F",
    subcategories: [
      { name: "African Travel", slug: "african-travel" },
      { name: "Travel Writing", slug: "travel-writing" },
      { name: "Travel Guides", slug: "travel-guides" },
      { name: "Adventure", slug: "adventure" },
    ],
    featuredBook: { title: "Around the World in 80 Days", author: "Jules Verne", slug: "around-the-world-in-80-days" },
  },
  {
    name: "Reference",
    slug: "reference",
    icon: "\uD83D\uDD17",
    subcategories: [
      { name: "Dictionaries", slug: "dictionaries" },
      { name: "Encyclopedias", slug: "encyclopedias" },
      { name: "Language Learning", slug: "language-learning" },
      { name: "Writing Guides", slug: "writing-guides" },
    ],
    featuredBook: { title: "The Elements of Style", author: "Strunk & White", slug: "the-elements-of-style" },
  },
];
