export interface DemoAuthor {
  id: string;
  name: string;
  penName: string;
  bio: string;
  avatar: string;
  bookCount: number;
  followers: number;
  slug: string;
}

export interface DemoCategory {
  id: string;
  name: string;
  slug: string;
  icon: string;
  bookCount: number;
  description: string;
}

export interface DemoBook {
  id: string;
  title: string;
  slug: string;
  author: DemoAuthor;
  category: DemoCategory;
  price: number;
  discountPrice: number | null;
  coverImage: string;
  averageRating: number;
  totalReviews: number;
  totalSales: number;
  description: string;
  format: string;
  isbn: string;
  pageCount: number;
  language: string;
  publicationDate: string;
  publisher: string;
  tags: string[];
  isNew: boolean;
  isBestseller: boolean;
  isFeatured: boolean;
  previewUrl?: string;
}

export const categories: DemoCategory[] = [
  { id: "c1", name: "Business & Entrepreneurship", slug: "business-entrepreneurship", icon: "💼", bookCount: 45, description: "Books on business strategy, startups, and entrepreneurship" },
  { id: "c2", name: "Personal Finance", slug: "personal-finance", icon: "💰", bookCount: 38, description: "Master your money with expert financial advice" },
  { id: "c3", name: "Self Development", slug: "self-development", icon: "🌱", bookCount: 52, description: "Transform your life with personal growth books" },
  { id: "c4", name: "Leadership", slug: "leadership", icon: "👑", bookCount: 31, description: "Develop your leadership skills and inspire others" },
  { id: "c5", name: "Technology", slug: "technology", icon: "💻", bookCount: 42, description: "Stay ahead with tech and digital transformation" },
  { id: "c6", name: "Religion & Inspiration", slug: "religion-inspiration", icon: "✨", bookCount: 29, description: "Spiritual growth and inspirational reads" },
  { id: "c7", name: "Education", slug: "education", icon: "🎓", bookCount: 35, description: "Learning resources and educational materials" },
  { id: "c8", name: "Biography", slug: "biography", icon: "👤", bookCount: 27, description: "True stories of remarkable lives" },
  { id: "c9", name: "Health & Wellness", slug: "health-wellness", icon: "🏥", bookCount: 33, description: "Books for a healthier, happier life" },
  { id: "c10", name: "Politics", slug: "politics", icon: "🏛️", bookCount: 22, description: "Political science and current affairs" },
  { id: "c11", name: "History", slug: "history", icon: "📜", bookCount: 28, description: "Explore the events that shaped our world" },
  { id: "c12", name: "Science", slug: "science", icon: "🔬", bookCount: 25, description: "Discoveries and scientific breakthroughs" },
  { id: "c13", name: "Productivity", slug: "productivity", icon: "⚡", bookCount: 30, description: "Get more done with less effort" },
  { id: "c14", name: "Marketing", slug: "marketing", icon: "📣", bookCount: 26, description: "Marketing strategies and brand building" },
  { id: "c15", name: "Fiction", slug: "fiction", icon: "📖", bookCount: 48, description: "Imaginative stories and literary fiction" },
  { id: "c16", name: "Non-Fiction", slug: "non-fiction", icon: "📚", bookCount: 55, description: "Informative and factual reads" },
  { id: "c17", name: "Children's Books", slug: "childrens-books", icon: "🧒", bookCount: 20, description: "Stories for young readers" },
  { id: "c18", name: "Romance", slug: "romance", icon: "💕", bookCount: 34, description: "Love stories and romantic fiction" },
  { id: "c19", name: "Mystery", slug: "mystery", icon: "🔍", bookCount: 23, description: "Thrilling mysteries and suspense" },
  { id: "c20", name: "Fantasy", slug: "fantasy", icon: "🐉", bookCount: 21, description: "Magical worlds and epic adventures" },
];

export const authors: DemoAuthor[] = [
  { id: "a1", name: "Sarah Mitchell", penName: "Sarah Mitchell", bio: "Award-winning author of literary fiction and personal finance books.", avatar: "", bookCount: 8, followers: 1240, slug: "sarah-mitchell" },
  { id: "a2", name: "James Okonkwo", penName: "J. Okonkwo", bio: "Nigerian-born entrepreneur and business strategist.", avatar: "", bookCount: 6, followers: 890, slug: "james-okonkwo" },
  { id: "a3", name: "Emily Chen", penName: "Emily Chen", bio: "Tech industry veteran turned author and consultant.", avatar: "", bookCount: 5, followers: 720, slug: "emily-chen" },
  { id: "a4", name: "David Adebayo", penName: "D. Adebayo", bio: "Leadership coach and bestselling author on management.", avatar: "", bookCount: 7, followers: 1100, slug: "david-adebayo" },
  { id: "a5", name: "Rachel Thompson", penName: "R. Thompson", bio: "Self-help author specializing in mindfulness and productivity.", avatar: "", bookCount: 4, followers: 650, slug: "rachel-thompson" },
  { id: "a6", name: "Michael Rivera", penName: "M. Rivera", bio: "Historian and professor of African studies.", avatar: "", bookCount: 5, followers: 580, slug: "michael-rivera" },
  { id: "a7", name: "Grace Adeyemi", penName: "G. Adeyemi", bio: "Romance novelist with a passion for love stories.", avatar: "", bookCount: 9, followers: 1560, slug: "grace-adeyemi" },
  { id: "a8", name: "Robert Kimani", penName: "R. Kimani", bio: "Science fiction author exploring African futures.", avatar: "", bookCount: 6, followers: 830, slug: "robert-kimani" },
  { id: "a9", name: "Fatima Al-Rashid", penName: "F. Al-Rashid", bio: "Award-winning journalist and non-fiction writer.", avatar: "", bookCount: 4, followers: 670, slug: "fatima-al-rashid" },
  { id: "a10", name: "Thomas Bello", penName: "T. Bello", bio: "Children's book author and illustrator.", avatar: "", bookCount: 7, followers: 920, slug: "thomas-bello" },
  { id: "a11", name: "Angela Nwosu", penName: "A. Nwosu", bio: "Health and wellness advocate, certified nutritionist.", avatar: "", bookCount: 5, followers: 780, slug: "angela-nwosu" },
  { id: "a12", name: "Patrick Osei", penName: "P. Osei", bio: "Marketing guru and brand strategist.", avatar: "", bookCount: 4, followers: 540, slug: "patrick-osei" },
  { id: "a13", name: "Linda Mensah", penName: "L. Mensah", bio: "Poet and literary fiction writer.", avatar: "", bookCount: 6, followers: 690, slug: "linda-mensah" },
  { id: "a14", name: "Samuel Eze", penName: "S. Eze", bio: "Religious scholar and inspirational speaker.", avatar: "", bookCount: 5, followers: 810, slug: "samuel-eze" },
  { id: "a15", name: "Nina Adekunle", penName: "N. Adekunle", bio: "Education specialist and curriculum developer.", avatar: "", bookCount: 3, followers: 420, slug: "nina-adekunle" },
  { id: "a16", name: "Oscar Dube", penName: "O. Dube", bio: "Mystery and thriller writer from South Africa.", avatar: "", bookCount: 5, followers: 760, slug: "oscar-dube" },
  { id: "a17", name: "Christine Ibe", penName: "C. Ibe", bio: "Productivity coach and time management expert.", avatar: "", bookCount: 4, followers: 530, slug: "christine-ibe" },
  { id: "a18", name: "Benjamin Asare", penName: "B. Asare", bio: "Political commentator and author.", avatar: "", bookCount: 3, followers: 380, slug: "benjamin-asare" },
  { id: "a19", name: "Zainab Hassan", penName: "Z. Hassan", bio: "Fantasy novelist building worlds inspired by African mythology.", avatar: "", bookCount: 4, followers: 620, slug: "zainab-hassan" },
  { id: "a20", name: "Daniel Okafor", penName: "D. Okafor", bio: "Personal finance expert and investment advisor.", avatar: "", bookCount: 5, followers: 910, slug: "daniel-okafor" },
];

function generateCover(title: string, color: string): string {
  return `https://placehold.co/400x600/${color}/ffffff?text=${encodeURIComponent(title.slice(0, 20))}`;
}

const coverColors = ["8A6A4A", "D8B27A", "1D1D1D", "4A6A8A", "6A8A4A", "8A4A6A", "4A4A8A", "8A8A4A", "2D5A3D", "5D3D6A", "3D5A6A", "6A3D5D"];

export const books: DemoBook[] = [
  { id: "b1", title: "Financial Freedom Blueprint", slug: "financial-freedom-blueprint", author: authors[0], category: categories[1], price: 14.99, discountPrice: 9.99, coverImage: generateCover("Financial Freedom", coverColors[0]), averageRating: 4.8, totalReviews: 234, totalSales: 3420, description: "A comprehensive guide to achieving financial independence through smart investing, budgeting, and wealth-building strategies. Sarah Mitchell shares proven methods that have helped thousands of readers take control of their financial future.", format: "EBOOK", isbn: "978-1-234567-01-1", pageCount: 320, language: "English", publicationDate: "2025-03-15", publisher: "Statement Publications", tags: ["finance", "investing", "wealth"], isNew: false, isBestseller: true, isFeatured: true },
  { id: "b2", title: "The Wealth Blueprint", slug: "the-wealth-blueprint", author: authors[0], category: categories[1], price: 12.99, discountPrice: null, coverImage: generateCover("Wealth Blueprint", coverColors[1]), averageRating: 4.6, totalReviews: 189, totalSales: 2870, description: "Build lasting wealth with this step-by-step guide to financial planning, investment strategies, and money management.", format: "EBOOK", isbn: "978-1-234567-02-8", pageCount: 280, language: "English", publicationDate: "2024-11-20", publisher: "Statement Publications", tags: ["finance", "wealth", "planning"], isNew: false, isBestseller: true, isFeatured: false },
  { id: "b3", title: "African Entrepreneurship Rising", slug: "african-entrepreneurship-rising", author: authors[1], category: categories[0], price: 16.99, discountPrice: 12.99, coverImage: generateCover("African Entrepreneurship", coverColors[2]), averageRating: 4.7, totalReviews: 156, totalSales: 2100, description: "Explore the booming African startup ecosystem and discover how entrepreneurs across the continent are building world-class businesses.", format: "EBOOK", isbn: "978-1-234567-03-5", pageCount: 350, language: "English", publicationDate: "2025-01-10", publisher: "Statement Publications", tags: ["entrepreneurship", "africa", "business"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b4", title: "Digital Transformation Playbook", slug: "digital-transformation-playbook", author: authors[2], category: categories[4], price: 18.99, discountPrice: 14.99, coverImage: generateCover("Digital Transformation", coverColors[3]), averageRating: 4.5, totalReviews: 98, totalSales: 1560, description: "A practical guide for businesses navigating the digital landscape. Learn how to leverage technology for competitive advantage.", format: "EBOOK", isbn: "978-1-234567-04-2", pageCount: 400, language: "English", publicationDate: "2025-02-28", publisher: "Statement Publications", tags: ["technology", "digital", "business"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b5", title: "Lead Like a Lion", slug: "lead-like-a-lion", author: authors[3], category: categories[3], price: 15.99, discountPrice: null, coverImage: generateCover("Lead Like a Lion", coverColors[4]), averageRating: 4.9, totalReviews: 312, totalSales: 4200, description: "Inspiring leadership lessons from nature's most powerful creature. Develop courage, vision, and the ability to inspire your team.", format: "EBOOK", isbn: "978-1-234567-05-9", pageCount: 260, language: "English", publicationDate: "2024-09-05", publisher: "Statement Publications", tags: ["leadership", "management", "inspiration"], isNew: false, isBestseller: true, isFeatured: true },
  { id: "b6", title: "The Mindful Morning", slug: "the-mindful-morning", author: authors[4], category: categories[2], price: 11.99, discountPrice: 7.99, coverImage: generateCover("Mindful Morning", coverColors[5]), averageRating: 4.4, totalReviews: 167, totalSales: 2340, description: "Transform your mornings with mindfulness practices that set the tone for a productive and peaceful day.", format: "EBOOK", isbn: "978-1-234567-06-6", pageCount: 192, language: "English", publicationDate: "2025-04-01", publisher: "Statement Publications", tags: ["mindfulness", "morning", "wellness"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b7", title: "Echoes of Benin Kingdom", slug: "echoes-of-benin-kingdom", author: authors[5], category: categories[10], price: 13.99, discountPrice: null, coverImage: generateCover("Echoes of Benin", coverColors[6]), averageRating: 4.7, totalReviews: 89, totalSales: 1120, description: "A fascinating journey through the history of the Benin Kingdom, exploring its art, politics, and lasting cultural impact.", format: "EBOOK", isbn: "978-1-234567-07-3", pageCount: 380, language: "English", publicationDate: "2024-08-15", publisher: "Statement Publications", tags: ["history", "africa", "culture"], isNew: false, isBestseller: false, isFeatured: true },
  { id: "b8", title: "Hearts in Lagos", slug: "hearts-in-lagos", author: authors[6], category: categories[17], price: 9.99, discountPrice: 6.99, coverImage: generateCover("Hearts in Lagos", coverColors[7]), averageRating: 4.3, totalReviews: 278, totalSales: 3890, description: "A sweeping romance set in the vibrant city of Lagos. Two strangers, one chance encounter, and a love that changes everything.", format: "EBOOK", isbn: "978-1-234567-08-0", pageCount: 310, language: "English", publicationDate: "2025-02-14", publisher: "Statement Publications", tags: ["romance", "lagos", "love"], isNew: true, isBestseller: true, isFeatured: true },
  { id: "b9", title: "Cybersecurity in Africa", slug: "cybersecurity-in-africa", author: authors[2], category: categories[4], price: 22.99, discountPrice: 17.99, coverImage: generateCover("Cybersecurity Africa", coverColors[8]), averageRating: 4.6, totalReviews: 67, totalSales: 890, description: "A comprehensive look at the cybersecurity landscape across Africa, with practical strategies for protection and resilience.", format: "EBOOK", isbn: "978-1-234567-09-7", pageCount: 420, language: "English", publicationDate: "2025-05-10", publisher: "Statement Publications", tags: ["cybersecurity", "africa", "technology"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b10", title: "The Alchemist of Abuja", slug: "the-alchemist-of-abuja", author: authors[7], category: categories[19], price: 10.99, discountPrice: null, coverImage: generateCover("Alchemist of Abuja", coverColors[9]), averageRating: 4.5, totalReviews: 145, totalSales: 1980, description: "A magical realism novel set in Abuja where a young alchemist discovers ancient powers that could reshape the nation.", format: "EBOOK", isbn: "978-1-234567-10-3", pageCount: 340, language: "English", publicationDate: "2024-12-01", publisher: "Statement Publications", tags: ["fantasy", "nigeria", "magic"], isNew: false, isBestseller: false, isFeatured: true },
  { id: "b11", title: "Breaking the Glass Ceiling", slug: "breaking-the-glass-ceiling", author: authors[8], category: categories[15], price: 14.99, discountPrice: 10.99, coverImage: generateCover("Breaking Glass Ceiling", coverColors[10]), averageRating: 4.8, totalReviews: 201, totalSales: 2670, description: "An inspiring collection of stories from women who shattered barriers in business, politics, and society.", format: "EBOOK", isbn: "978-1-234567-11-0", pageCount: 290, language: "English", publicationDate: "2025-03-08", publisher: "Statement Publications", tags: ["women", "empowerment", "non-fiction"], isNew: true, isBestseller: true, isFeatured: false },
  { id: "b12", title: "Adventures of Kito", slug: "adventures-of-kito", author: authors[9], category: categories[16], price: 7.99, discountPrice: null, coverImage: generateCover("Adventures of Kito", coverColors[11]), averageRating: 4.9, totalReviews: 156, totalSales: 2100, description: "Join Kito on exciting adventures across Africa as he learns about different cultures, animals, and the beauty of the continent.", format: "EBOOK", isbn: "978-1-234567-12-7", pageCount: 120, language: "English", publicationDate: "2025-01-20", publisher: "Statement Publications", tags: ["children", "africa", "adventure"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b13", title: "The Complete Guide to Healthy Living", slug: "complete-guide-healthy-living", author: authors[10], category: categories[8], price: 13.99, discountPrice: 9.99, coverImage: generateCover("Healthy Living Guide", coverColors[0]), averageRating: 4.4, totalReviews: 134, totalSales: 1890, description: "A holistic approach to health covering nutrition, exercise, mental wellness, and preventive care.", format: "EBOOK", isbn: "978-1-234567-13-4", pageCount: 350, language: "English", publicationDate: "2024-10-15", publisher: "Statement Publications", tags: ["health", "wellness", "nutrition"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b14", title: "Brand Mastery", slug: "brand-mastery", author: authors[11], category: categories[13], price: 16.99, discountPrice: 12.99, coverImage: generateCover("Brand Mastery", coverColors[1]), averageRating: 4.6, totalReviews: 89, totalSales: 1340, description: "Learn how to build a powerful brand that resonates with your audience and stands out in the marketplace.", format: "EBOOK", isbn: "978-1-234567-14-1", pageCount: 280, language: "English", publicationDate: "2025-04-20", publisher: "Statement Publications", tags: ["marketing", "branding", "business"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b15", title: "Whispers of the Night", slug: "whispers-of-the-night", author: authors[12], category: categories[14], price: 8.99, discountPrice: null, coverImage: generateCover("Whispers of Night", coverColors[2]), averageRating: 4.2, totalReviews: 112, totalSales: 1560, description: "A collection of hauntingly beautiful poems that explore love, loss, and the human condition.", format: "EBOOK", isbn: "978-1-234567-15-8", pageCount: 160, language: "English", publicationDate: "2024-07-01", publisher: "Statement Publications", tags: ["poetry", "literary", "emotions"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b16", title: "Walking in Purpose", slug: "walking-in-purpose", author: authors[13], category: categories[5], price: 11.99, discountPrice: 8.99, coverImage: generateCover("Walking in Purpose", coverColors[3]), averageRating: 4.7, totalReviews: 198, totalSales: 2450, description: "Discover your divine purpose and learn to walk in it with confidence. A spiritual guide to fulfilling your destiny.", format: "EBOOK", isbn: "978-1-234567-16-5", pageCount: 240, language: "English", publicationDate: "2025-02-01", publisher: "Statement Publications", tags: ["spiritual", "purpose", "faith"], isNew: true, isBestseller: true, isFeatured: false },
  { id: "b17", title: "The Future of African Education", slug: "future-african-education", author: authors[14], category: categories[6], price: 15.99, discountPrice: null, coverImage: generateCover("Future Education", coverColors[4]), averageRating: 4.3, totalReviews: 67, totalSales: 890, description: "Examining innovative approaches to education across Africa and envisioning the future of learning on the continent.", format: "EBOOK", isbn: "978-1-234567-17-2", pageCount: 310, language: "English", publicationDate: "2024-11-10", publisher: "Statement Publications", tags: ["education", "africa", "future"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b18", title: "The Last Detective", slug: "the-last-detective", author: authors[15], category: categories[18], price: 10.99, discountPrice: 7.99, coverImage: generateCover("Last Detective", coverColors[5]), averageRating: 4.5, totalReviews: 178, totalSales: 2230, description: "A gripping mystery set in Cape Town where a retired detective is drawn into one final, dangerous case.", format: "EBOOK", isbn: "978-1-234567-18-9", pageCount: 330, language: "English", publicationDate: "2025-03-20", publisher: "Statement Publications", tags: ["mystery", "thriller", "detective"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b19", title: "Time Mastery System", slug: "time-mastery-system", author: authors[16], category: categories[12], price: 12.99, discountPrice: 8.99, coverImage: generateCover("Time Mastery", coverColors[6]), averageRating: 4.6, totalReviews: 145, totalSales: 1980, description: "A proven system for managing your time effectively and achieving more in less time.", format: "EBOOK", isbn: "978-1-234567-19-6", pageCount: 220, language: "English", publicationDate: "2025-01-15", publisher: "Statement Publications", tags: ["productivity", "time-management", "efficiency"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b20", title: "Voice of the People", slug: "voice-of-the-people", author: authors[17], category: categories[9], price: 14.99, discountPrice: null, coverImage: generateCover("Voice of People", coverColors[7]), averageRating: 4.4, totalReviews: 78, totalSales: 1120, description: "A thought-provoking analysis of democratic movements across Africa and their impact on governance.", format: "EBOOK", isbn: "978-1-234567-20-2", pageCount: 360, language: "English", publicationDate: "2024-06-15", publisher: "Statement Publications", tags: ["politics", "democracy", "africa"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b21", title: "Kingdoms of Sand and Stars", slug: "kingdoms-sand-stars", author: authors[18], category: categories[19], price: 11.99, discountPrice: 8.99, coverImage: generateCover("Kingdoms Sand Stars", coverColors[8]), averageRating: 4.8, totalReviews: 234, totalSales: 3100, description: "An epic fantasy saga inspired by African mythology, following a young warrior's quest to save her kingdom.", format: "EBOOK", isbn: "978-1-234567-21-9", pageCount: 420, language: "English", publicationDate: "2025-05-01", publisher: "Statement Publications", tags: ["fantasy", "african", "mythology"], isNew: true, isBestseller: true, isFeatured: true },
  { id: "b22", title: "Smart Money Moves", slug: "smart-money-moves", author: authors[19], category: categories[1], price: 13.99, discountPrice: 9.99, coverImage: generateCover("Smart Money Moves", coverColors[9]), averageRating: 4.5, totalReviews: 167, totalSales: 2340, description: "Practical financial advice for young professionals looking to build wealth and secure their future.", format: "EBOOK", isbn: "978-1-234567-22-6", pageCount: 250, language: "English", publicationDate: "2025-04-10", publisher: "Statement Publications", tags: ["finance", "investing", "young-adults"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b23", title: "Startup Africa", slug: "startup-africa", author: authors[1], category: categories[0], price: 17.99, discountPrice: 13.99, coverImage: generateCover("Startup Africa", coverColors[10]), averageRating: 4.7, totalReviews: 123, totalSales: 1780, description: "The definitive guide to building successful startups in Africa, from ideation to scaling across the continent.", format: "EBOOK", isbn: "978-1-234567-23-3", pageCount: 380, language: "English", publicationDate: "2024-12-10", publisher: "Statement Publications", tags: ["startup", "africa", "entrepreneurship"], isNew: false, isBestseller: true, isFeatured: true },
  { id: "b24", title: "The Art of Communication", slug: "art-of-communication", author: authors[3], category: categories[3], price: 14.99, discountPrice: null, coverImage: generateCover("Art of Communication", coverColors[11]), averageRating: 4.6, totalReviews: 156, totalSales: 2100, description: "Master the art of effective communication in business and personal relationships.", format: "EBOOK", isbn: "978-1-234567-24-0", pageCount: 270, language: "English", publicationDate: "2025-02-20", publisher: "Statement Publications", tags: ["communication", "leadership", "skills"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b25", title: "Blockchain Revolution Africa", slug: "blockchain-revolution-africa", author: authors[2], category: categories[4], price: 19.99, discountPrice: 14.99, coverImage: generateCover("Blockchain Africa", coverColors[0]), averageRating: 4.4, totalReviews: 78, totalSales: 1020, description: "How blockchain technology is transforming finance, governance, and society across Africa.", format: "EBOOK", isbn: "978-1-234567-25-7", pageCount: 390, language: "English", publicationDate: "2025-06-01", publisher: "Statement Publications", tags: ["blockchain", "technology", "africa"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b26", title: "Love in the Time of Jollof", slug: "love-time-jollof", author: authors[6], category: categories[17], price: 8.99, discountPrice: 5.99, coverImage: generateCover("Love Jollof", coverColors[1]), averageRating: 4.3, totalReviews: 245, totalSales: 3450, description: "A heartwarming romance set in Accra where two food bloggers fall in love over their shared passion for West African cuisine.", format: "EBOOK", isbn: "978-1-234567-26-4", pageCount: 280, language: "English", publicationDate: "2024-12-25", publisher: "Statement Publications", tags: ["romance", "ghana", "food"], isNew: false, isBestseller: true, isFeatured: false },
  { id: "b27", title: "Quantum Computing Simplified", slug: "quantum-computing-simplified", author: authors[2], category: categories[11], price: 21.99, discountPrice: 16.99, coverImage: generateCover("Quantum Computing", coverColors[2]), averageRating: 4.5, totalReviews: 56, totalSales: 780, description: "Making quantum computing accessible to everyone. No physics degree required.", format: "EBOOK", isbn: "978-1-234567-27-1", pageCount: 340, language: "English", publicationDate: "2025-03-25", publisher: "Statement Publications", tags: ["quantum", "computing", "science"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b28", title: "Prayers That Move Mountains", slug: "prayers-move-mountains", author: authors[13], category: categories[5], price: 9.99, discountPrice: null, coverImage: generateCover("Prayers Mountains", coverColors[3]), averageRating: 4.8, totalReviews: 312, totalSales: 4560, description: "A powerful collection of prayers and affirmations for every area of life.", format: "EBOOK", isbn: "978-1-234567-28-8", pageCount: 180, language: "English", publicationDate: "2024-08-01", publisher: "Statement Publications", tags: ["prayer", "faith", "spiritual"], isNew: false, isBestseller: true, isFeatured: false },
  { id: "b29", title: "The Mystery of Nairobi Nights", slug: "mystery-nairobi-nights", author: authors[15], category: categories[18], price: 10.99, discountPrice: 7.99, coverImage: generateCover("Nairobi Nights", coverColors[4]), averageRating: 4.4, totalReviews: 134, totalSales: 1890, description: "A detective thriller set in the pulsing nightlife of Nairobi, where nothing is as it seems.", format: "EBOOK", isbn: "978-1-234567-29-5", pageCount: 310, language: "English", publicationDate: "2025-05-15", publisher: "Statement Publications", tags: ["mystery", "thriller", "kenya"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b30", title: "Zero to One in Africa", slug: "zero-to-one-africa", author: authors[1], category: categories[0], price: 16.99, discountPrice: 12.99, coverImage: generateCover("Zero to One Africa", coverColors[5]), averageRating: 4.6, totalReviews: 145, totalSales: 1980, description: "Building innovative businesses from scratch in the African context. Practical lessons from the trenches.", format: "EBOOK", isbn: "978-1-234567-30-1", pageCount: 320, language: "English", publicationDate: "2025-01-25", publisher: "Statement Publications", tags: ["startup", "innovation", "africa"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b31", title: "The Productivity Journal", slug: "productivity-journal", author: authors[16], category: categories[12], price: 11.99, discountPrice: 8.99, coverImage: generateCover("Productivity Journal", coverColors[6]), averageRating: 4.5, totalReviews: 189, totalSales: 2670, description: "A 90-day guided journal to help you build powerful habits and achieve your biggest goals.", format: "EBOOK", isbn: "978-1-234567-31-8", pageCount: 200, language: "English", publicationDate: "2025-04-15", publisher: "Statement Publications", tags: ["productivity", "journal", "habits"], isNew: true, isBestseller: true, isFeatured: false },
  { id: "b32", title: "Stories from the Village", slug: "stories-from-village", author: authors[9], category: categories[16], price: 6.99, discountPrice: null, coverImage: generateCover("Stories Village", coverColors[7]), averageRating: 4.7, totalReviews: 134, totalSales: 1890, description: "Charming illustrated stories set in a Nigerian village, teaching children about community and kindness.", format: "EBOOK", isbn: "978-1-234567-32-5", pageCount: 96, language: "English", publicationDate: "2024-10-01", publisher: "Statement Publications", tags: ["children", "nigeria", "stories"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b33", title: "Digital Marketing Mastery", slug: "digital-marketing-mastery", author: authors[11], category: categories[13], price: 15.99, discountPrice: 11.99, coverImage: generateCover("Digital Marketing", coverColors[8]), averageRating: 4.4, totalReviews: 112, totalSales: 1560, description: "Master social media, SEO, email marketing, and paid advertising to grow your business online.", format: "EBOOK", isbn: "978-1-234567-33-2", pageCount: 300, language: "English", publicationDate: "2025-03-10", publisher: "Statement Publications", tags: ["marketing", "digital", "social-media"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b34", title: "The Healing Journey", slug: "healing-journey", author: authors[10], category: categories[8], price: 12.99, discountPrice: 8.99, coverImage: generateCover("Healing Journey", coverColors[9]), averageRating: 4.6, totalReviews: 167, totalSales: 2230, description: "A comprehensive guide to emotional healing and mental wellness, combining ancient wisdom with modern science.", format: "EBOOK", isbn: "978-1-234567-34-9", pageCount: 280, language: "English", publicationDate: "2025-02-25", publisher: "Statement Publications", tags: ["health", "healing", "mental-health"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b35", title: "Shadows of the Savanna", slug: "shadows-savanna", author: authors[7], category: categories[14], price: 9.99, discountPrice: null, coverImage: generateCover("Shadows Savanna", coverColors[10]), averageRating: 4.3, totalReviews: 98, totalSales: 1340, description: "A literary fiction novel exploring identity, belonging, and the complexities of modern African life.", format: "EBOOK", isbn: "978-1-234567-35-6", pageCount: 310, language: "English", publicationDate: "2024-09-20", publisher: "Statement Publications", tags: ["fiction", "literary", "africa"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b36", title: "Investing 101 for Africans", slug: "investing-101-africans", author: authors[19], category: categories[1], price: 10.99, discountPrice: 7.99, coverImage: generateCover("Investing 101", coverColors[11]), averageRating: 4.7, totalReviews: 234, totalSales: 3100, description: "A beginner-friendly guide to investing in African stock markets, real estate, and digital assets.", format: "EBOOK", isbn: "978-1-234567-36-3", pageCount: 240, language: "English", publicationDate: "2025-05-20", publisher: "Statement Publications", tags: ["investing", "finance", "africa"], isNew: true, isBestseller: true, isFeatured: true },
  { id: "b37", title: "The CEO's Playbook", slug: "ceos-playbook", author: authors[3], category: categories[3], price: 18.99, discountPrice: 14.99, coverImage: generateCover("CEO Playbook", coverColors[0]), averageRating: 4.8, totalReviews: 267, totalSales: 3560, description: "Essential strategies for executive leadership, from managing teams to driving organizational transformation.", format: "EBOOK", isbn: "978-1-234567-37-0", pageCount: 360, language: "English", publicationDate: "2024-11-25", publisher: "Statement Publications", tags: ["leadership", "ceo", "management"], isNew: false, isBestseller: true, isFeatured: true },
  { id: "b38", title: "Cooking with Love", slug: "cooking-with-love", author: authors[10], category: categories[8], price: 8.99, discountPrice: null, coverImage: generateCover("Cooking Love", coverColors[1]), averageRating: 4.5, totalReviews: 189, totalSales: 2670, description: "A healthy recipe book combining traditional African flavors with modern nutrition science.", format: "EBOOK", isbn: "978-1-234567-38-7", pageCount: 220, language: "English", publicationDate: "2025-01-05", publisher: "Statement Publications", tags: ["cooking", "health", "recipes"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b39", title: "The Education Revolution", slug: "education-revolution", author: authors[14], category: categories[6], price: 14.99, discountPrice: 10.99, coverImage: generateCover("Education Revolution", coverColors[2]), averageRating: 4.3, totalReviews: 78, totalSales: 1020, description: "How technology is transforming education in Africa and creating new opportunities for learners.", format: "EBOOK", isbn: "978-1-234567-39-4", pageCount: 290, language: "English", publicationDate: "2025-04-05", publisher: "Statement Publications", tags: ["education", "technology", "africa"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b40", title: "Desert Wind Chronicles", slug: "desert-wind-chronicles", author: authors[18], category: categories[19], price: 12.99, discountPrice: 9.99, coverImage: generateCover("Desert Wind", coverColors[3]), averageRating: 4.6, totalReviews: 156, totalSales: 2100, description: "An epic fantasy adventure through the Sahara, where ancient magic awakens and empires clash.", format: "EBOOK", isbn: "978-1-234567-40-0", pageCount: 400, language: "English", publicationDate: "2025-06-10", publisher: "Statement Publications", tags: ["fantasy", "adventure", "sahara"], isNew: true, isBestseller: false, isFeatured: true },
  { id: "b41", title: "Raising Financially Smart Kids", slug: "raising-financially-smart-kids", author: authors[0], category: categories[1], price: 11.99, discountPrice: 8.99, coverImage: generateCover("Smart Kids Finance", coverColors[4]), averageRating: 4.6, totalReviews: 178, totalSales: 2450, description: "Teach your children about money management from an early age with practical activities and conversations.", format: "EBOOK", isbn: "978-1-234567-41-7", pageCount: 210, language: "English", publicationDate: "2025-03-01", publisher: "Statement Publications", tags: ["finance", "parenting", "children"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b42", title: "The Art of Negotiation", slug: "art-of-negotiation", author: authors[3], category: categories[3], price: 13.99, discountPrice: null, coverImage: generateCover("Art Negotiation", coverColors[5]), averageRating: 4.5, totalReviews: 145, totalSales: 1980, description: "Master the skill of negotiation in business and life. Proven tactics for getting what you want.", format: "EBOOK", isbn: "978-1-234567-42-4", pageCount: 260, language: "English", publicationDate: "2024-10-20", publisher: "Statement Publications", tags: ["negotiation", "business", "skills"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b43", title: "Seeds of Hope", slug: "seeds-of-hope", author: authors[13], category: categories[5], price: 9.99, discountPrice: 6.99, coverImage: generateCover("Seeds Hope", coverColors[6]), averageRating: 4.7, totalReviews: 201, totalSales: 2780, description: "An inspirational book about finding hope and strength in difficult times through faith and perseverance.", format: "EBOOK", isbn: "978-1-234567-43-1", pageCount: 190, language: "English", publicationDate: "2025-02-10", publisher: "Statement Publications", tags: ["inspiration", "faith", "hope"], isNew: true, isBestseller: true, isFeatured: false },
  { id: "b44", title: "The Science of Sleep", slug: "science-of-sleep", author: authors[10], category: categories[11], price: 14.99, discountPrice: 10.99, coverImage: generateCover("Science Sleep", coverColors[7]), averageRating: 4.4, totalReviews: 112, totalSales: 1560, description: "Discover the science behind quality sleep and learn evidence-based strategies for better rest.", format: "EBOOK", isbn: "978-1-234567-44-8", pageCount: 270, language: "English", publicationDate: "2025-04-25", publisher: "Statement Publications", tags: ["science", "health", "sleep"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b45", title: "Lagos After Dark", slug: "lagos-after-dark", author: authors[6], category: categories[18], price: 9.99, discountPrice: null, coverImage: generateCover("Lagos After Dark", coverColors[8]), averageRating: 4.2, totalReviews: 198, totalSales: 2890, description: "A steamy romance set in Lagos's vibrant nightlife scene. Two strangers, one unforgettable night.", format: "EBOOK", isbn: "978-1-234567-45-5", pageCount: 290, language: "English", publicationDate: "2024-07-14", publisher: "Statement Publications", tags: ["romance", "lagos", "nightlife"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b46", title: "Climate Change and Africa", slug: "climate-change-africa", author: authors[5], category: categories[11], price: 16.99, discountPrice: 12.99, coverImage: generateCover("Climate Africa", coverColors[9]), averageRating: 4.5, totalReviews: 67, totalSales: 890, description: "Understanding the impact of climate change on Africa and solutions for a sustainable future.", format: "EBOOK", isbn: "978-1-234567-46-2", pageCount: 340, language: "English", publicationDate: "2025-05-05", publisher: "Statement Publications", tags: ["climate", "environment", "africa"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b47", title: "The Power of Habit", slug: "power-of-habit", author: authors[4], category: categories[2], price: 12.99, discountPrice: 8.99, coverImage: generateCover("Power of Habit", coverColors[10]), averageRating: 4.6, totalReviews: 234, totalSales: 3200, description: "Transform your life by understanding how habits work and how to change them for good.", format: "EBOOK", isbn: "978-1-234567-47-9", pageCount: 280, language: "English", publicationDate: "2025-01-30", publisher: "Statement Publications", tags: ["habits", "self-help", "change"], isNew: true, isBestseller: true, isFeatured: true },
  { id: "b48", title: "Tales of the Moonlit River", slug: "tales-moonlit-river", author: authors[12], category: categories[14], price: 7.99, discountPrice: null, coverImage: generateCover("Moonlit River", coverColors[11]), averageRating: 4.4, totalReviews: 89, totalSales: 1230, description: "A beautifully crafted short story collection exploring love, loss, and redemption along a mythical river.", format: "EBOOK", isbn: "978-1-234567-48-6", pageCount: 180, language: "English", publicationDate: "2024-06-01", publisher: "Statement Publications", tags: ["fiction", "short-stories", "literary"], isNew: false, isBestseller: false, isFeatured: false },
  { id: "b49", title: "Social Media for Authors", slug: "social-media-authors", author: authors[11], category: categories[13], price: 11.99, discountPrice: 8.99, coverImage: generateCover("Social Media Authors", coverColors[0]), averageRating: 4.3, totalReviews: 112, totalSales: 1560, description: "Build your author platform and connect with readers through social media marketing.", format: "EBOOK", isbn: "978-1-234567-49-3", pageCount: 220, language: "English", publicationDate: "2025-03-15", publisher: "Statement Publications", tags: ["marketing", "social-media", "authors"], isNew: true, isBestseller: false, isFeatured: false },
  { id: "b50", title: "The Entrepreneur's Mindset", slug: "entrepreneurs-mindset", author: authors[1], category: categories[0], price: 14.99, discountPrice: 10.99, coverImage: generateCover("Entrepreneur Mindset", coverColors[1]), averageRating: 4.7, totalReviews: 189, totalSales: 2670, description: "Develop the mindset of a successful entrepreneur. Overcome fear, embrace failure, and achieve your dreams.", format: "EBOOK", isbn: "978-1-234567-50-9", pageCount: 280, language: "English", publicationDate: "2025-04-30", publisher: "Statement Publications", tags: ["entrepreneurship", "mindset", "business"], isNew: true, isBestseller: true, isFeatured: true },
];

export function getBooksByCategory(categorySlug: string): DemoBook[] {
  return books.filter((b) => b.category.slug === categorySlug);
}

export function getBooksByAuthor(authorSlug: string): DemoBook[] {
  return books.filter((b) => b.author.slug === authorSlug);
}

export function getBookBySlug(slug: string): DemoBook | undefined {
  return books.find((b) => b.slug === slug);
}

export function getAuthorBySlug(slug: string): DemoAuthor | undefined {
  return authors.find((a) => a.slug === slug);
}

export function getCategoryBySlug(slug: string): DemoCategory | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getFeaturedBooks(): DemoBook[] {
  return books.filter((b) => b.isFeatured);
}

export function getBestsellerBooks(): DemoBook[] {
  return books.filter((b) => b.isBestseller);
}

export function getNewReleases(): DemoBook[] {
  return books.filter((b) => b.isNew);
}

export function searchBooks(query: string): DemoBook[] {
  const q = query.toLowerCase();
  return books.filter(
    (b) =>
      b.title.toLowerCase().includes(q) ||
      b.author.name.toLowerCase().includes(q) ||
      b.category.name.toLowerCase().includes(q) ||
      b.tags.some((t) => t.toLowerCase().includes(q))
  );
}
